[project]
name = "transformer"
version = "0.1.0"
description = "Building the Transformer architecture from scratch"
requires-python = ">=3.12"
dependencies = [
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.6",
    "oc-render",
    "pandas>=3.0.1",
    "plotly>=6.5.2",
    "rich>=14.3.3",
    "torch>=2.5.0",
]

[tool.uv.sources]
oc-render = { path = "../../../../../oc-render", editable = true }
